module.exports = {
  plugins: ['@ianvs/prettier-plugin-sort-imports'],
  singleQuote: true,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  trailingComma: 'es5',
  printWidth: 100,
  bracketSpacing: true,
  bracketSameLine: false,
  arrowParens: 'always',
  proseWrap: 'preserve',
  endOfLine: 'auto',
  importOrder: ['<TYPES>', '', '^../(.*)$', '^./(.*)$'],
  importOrderParserPlugins: ['typescript'],
  importOrderTypeScriptVersion: '5.0.0',
};
